# nonk8s
---
# deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bank
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bank
  template:
    metadata:
      labels:
        app: bank
    spec:
      containers:
        - name: bank
          image: cwj/bank:v1
          ports:
            - containerPort: 8080

---
# service
kind: Service
apiVersion: v1
metadata:
  name: bank
  namespace: default
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8080
  selector:
    app: bank
  type: NodePort
