---
# deployment
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: bank
  namespace: default
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: bank
    spec:
      containers:
        - name: bank
          image: cwj/bank:latest
          ports:
            - containerPort: 80

---
# service
kind: Service
apiVersion: v1
metadata:
  name: bank
  namespace: default
spec:
  ports:
    - name: http
      port: 80
      targetPort: 80
  selector:
    app: bank
  type: NodePort
